export const ConfigListObject = [
      {
        'id': 0,
        'name': 'Fancy Work Station',
        'cpu': 'Intel Core i9 13900K',
        'cpu_brand': 'Intel',
        'gpu': 'Nvidia Gefroce RTX 4070Ti',
        'ram': '32GB Gskill Trident-Z',
        'motherboard': 'Asus ROG Strix B790',
        'case': 'Fractal Design North TG',
        'cpu_cooler': 'Noctua NH-D-15',
        'psu': 'EVGA 700W 80+ Platinum',
        'ssd': '1TB Samsung NvMe',
        'hdd': '4TB Seagate IronWolf 7200RPM'
      },
      {
        'id': 1,
        'name': 'ITX Work Station',
        'cpu': 'AMD Ryzen 5 3600',
        'cpu_brand': 'AMD',
        'gpu': 'Nvidia Gefroce RTX 4090',
        'ram': '32GB Gskill Trident-Z',
        'motherboard': 'Asus ROG Strix B790',
        'case': 'Fractal Design North TG',
        'cpu_cooler': 'Noctua NH-D-15',
        'psu': 'EVGA 700W 80+ Platinum',
        'ssd': '1TB Samsung NvMe',
        'hdd': '4TB Seagate IronWolf 7200RPM'
      },
      {
        'id': 2,
        'name': 'Asus prebuild',
        'cpu': 'AMD Ryzen 5 3600',
        'cpu_brand': 'AMD',
        'gpu': 'Nvidia Gefroce RTX 4090',
        'ram': '32GB Gskill Trident-Z',
        'motherboard': 'Asus ROG Strix B790',
        'case': 'Fractal Design North TG',
        'cpu_cooler': 'Noctua NH-D-15',
        'psu': 'EVGA 700W 80+ Platinum',
        'ssd': '1TB Samsung NvMe',
        'hdd': '4TB Seagate IronWolf 7200RPM'
      },
      {
        'id': 3,
        'name': 'Acer triton',
        'cpu': 'AMD Ryzen 5 3600',
        'cpu_brand': 'AMD',
        'gpu': 'Nvidia Gefroce RTX 4090',
        'ram': '32GB Gskill Trident-Z',
        'motherboard': 'Asus ROG Strix B790',
        'case': 'Fractal Design North TG',
        'cpu_cooler': 'Noctua NH-D-15',
        'psu': 'EVGA 700W 80+ Platinum',
        'ssd': '1TB Samsung NvMe',
        'hdd': '4TB Seagate IronWolf 7200RPM'
      },
    ]